serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://auth.learny.local/hydra
  consent: http://localhost:5555/consent
  login: http://localhost:5555/login
  logout: http://localhost:5555/logout
  registration: http://localhost:5555/signup
  # error: http://auth.learny.local/error

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
