services:
  auth-gateway:
    build:
      context: ../../auth-gateway
      dockerfile: docker/Dockerfile
    networks:
      - intranet
    restart: "no"
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433
      - KRATOS_ADMIN_URL=http://kratos:4434
      - HYDRA_ADMIN_URL=http://hydra:4445
      - HYDRA_PUBLIC_URL=http://auth.learny.local/hydra

  auth-gateway-ui:
    build:
      context: ../../auth-ui
      dockerfile: deploy/Dockerfile
    networks:
      - intranet
    restart: "no"
    environment:
      - VITE_GATEWAY_URL=http://auth.learny.local/api
