http:
  routers:
    # ───── Go API ──────────────────────────────────────────────
    api:
      rule: "Host(`auth.learny.local`) && PathPrefix(`/api`)"
      entryPoints: ["web"]
      service: "api"
      middlewares:
        - api-strip-prefix

    # ───── Auth (if needed as separate frontend) ──────────────
    auth:
      rule: "Host(`auth.learny.local`)"
      entryPoints: ["web"]
      service: "auth"

    # ───── ORY Hydra (public) ─────────────────────────────────
    hydra:
      rule: "Host(`hydra.learny.local`)"
      entryPoints: ["web"]
      service: "hydra"

    # ───── ORY Kratos (if needed) ─────────────────────────────
    kratos:
      rule: "Host(`kratos.learny.local`)"
      entryPoints: ["web"]
      service: "kratos"

  middlewares:
    api-strip-prefix:
      stripPrefix:
        prefixes:
          - /api

  services:
    # target ports must match your docker-compose service definitions
    api:
      loadBalancer:
        servers:
          - url: "http://auth-gateway:9941"
        passHostHeader: true

    auth:
      loadBalancer:
        servers:
          - url: "http://auth-gateway-ui:3000"
        passHostHeader: true

    hydra:
      loadBalancer:
        servers:
          - url: "http://hydra:4444"
        passHostHeader: true

    kratos:
      loadBalancer:
        servers:
          - url: "http://kratos:4433"
        passHostHeader: true
