# traefik/rules.yml

http:
  routers:
    oathkeeper:
      rule: "Host(`oathkeeper.localhost`)"
      entryPoints:
        - web
      service: oathkeeper

    kratos:
      rule: "Host(`kratos.localhost`)"
      entryPoints:
        - web
      service: kratos

    echo:
      rule: "Host(`echo.localhost`)"
      entryPoints:
        - web
      middlewares:
        - oathkeeper-auth
      service: echo
    
    bff:
      rule: "Host(`bff.localhost`)"
      entryPoints:
        - web
      middlewares:
        - oathkeeper-auth
      service: bff
    
    ui:
      rule: "Host(`ui.localhost`)"
      entryPoints:
        - web
      service: ui

  services:
    kratos:
      loadBalancer:
        servers:
          - url: "http://kratos:4433"
    oathkeeper:
      loadBalancer:
        servers:
          - url: "http://oathkeeper:4456"
    echo:
      loadBalancer:
        servers:
          - url: "http://echo:8080"
    
    ui:
      loadBalancer:
        servers:
          - url: "http://kratos-selfservice-ui-node:3000"

  middlewares:
    oathkeeper-auth:
      forwardAuth:
        address: "http://oathkeeper:4456/decisions"
        authResponseHeaders:
          - "Authorization"
        authRequestHeaders:
          - "Authorization"
