http:
  routers:
    api:
      rule: "Host(`auth.learny.local`) && PathPrefix(`/api`)"
      entryPoints: ["web"]
      service: "api"
      middlewares:
        - api-strip-prefix

    hydra:
      rule: "Host(`auth.learny.local`) && PathPrefix(`/hydra`)"
      entryPoints: ["web"]
      service: "hydra"
      middlewares:
        - hydra-strip-prefix

    auth:
      rule: "Host(`auth.learny.local`)"
      entryPoints: ["web"]
      service: "auth"

  middlewares:
    api-strip-prefix:
      stripPrefix:
        prefixes:
          - /api
    hydra-strip-prefix:
      stripPrefix:
        prefixes:
          - /hydra

  services:
    # target ports must match your docker-compose service definitions
    api:
      loadBalancer:
        servers:
          - url: "http://auth-gateway:9941"
        passHostHeader: true

    auth:
      loadBalancer:
        servers:
          - url: "http://auth-gateway-ui:3000"
        passHostHeader: true

    hydra:
      loadBalancer:
        servers:
          - url: "http://hydra:4444"
        passHostHeader: true

    kratos:
      loadBalancer:
        servers:
          - url: "http://kratos:4433"
        passHostHeader: true
