serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://auth.learny.local/hydra
  consent: http://auth.learny.local/consent
  login: http://auth.learny.local/login
  logout: http://auth.learny.local/logout
  registration: http://auth.learny.local/signup
  # error: http://auth.learny.local/error

secrets:
  system:
    - youReallyNeedToChangeThis

oidc:
  subject_identifiers:
    supported_types:
      - pairwise
      - public
    pairwise:
      salt: youReallyNeedToChangeThis
