- id: kratos-public
  match:
    url: "http://kratos.localhost/<**>"
    methods: ["GET", "POST", "PUT", "DELETE"]
  authenticators:
    - handler: anonymous
  authorizer:
    handler: allow
  mutators:
    - handler: noop

- id: echo-private
  match:
    url: "http://echo.localhost/<**>"
    methods: ["GET", "POST", "PUT", "DELETE"]
  authenticators:
    - handler: bearer_token
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
