version: v1.3.0

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: http://127.0.0.1:5555/welcome
  allowed_return_urls:
    - http://127.0.0.1:5555
    - http://127.0.0.1:5555/callback
  methods:
    code:
      passwordless_enabled: true
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:5555/error

    settings:
      ui_url: http://127.0.0.1:5555/settings

    login:
      ui_url: http://127.0.0.1:5555/login
      lifespan: 10m

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:5555/login

    registration:
      lifespan: 10m
      enabled: true
      ui_url: http://127.0.0.1:5555/signup
      after:
        code:
          hooks:
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

courier:
  message_retries: 5
  delivery_strategy: smtp
  smtp:
    # connection_uri is supplied from ENV
    # from_address is supplied from ENV
    from_name: Learny
    local_name: learny

cookies:
  same_site: Lax

session:
  cookie:
    name: ory_kratos_session
    persistent: true
    same_site: Lax
  lifespan: "24h"
